table Medidas
	lineageTag: 1316812e-1972-4115-96d2-a2c3ce9995f7

	measure TotalReceita = CALCULATE(SUM(DadosFinanceiros[Valor]), DadosFinanceiros[Tipo] = "Receitas")
		lineageTag: 4cd8e04f-f008-44d9-b480-bcbc5fe0d1d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Despesas' = ```
			CALCULATE(SUM(DadosFinanceiros[Valor]), DadosFinanceiros[Tipo] = "Despesas")
			
			```
		lineageTag: 63658e5c-b457-45b4-a92c-02e3e13a1a90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MargemLucro = CALCULATE(([TotalReceita] - [Total Despesas]) / [TotalReceita])
		lineageTag: 968c9cf1-f39c-432e-9901-2d32fe0afd5c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Lucro = CALCULATE([TotalReceita] - [Total Despesas])
		lineageTag: cb9281fe-dbf8-4e93-a06e-ec2643cb8237

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

